### ISSUE TITLE
Teams recipe run fails

### ISSUE THREAD

**Issue by opus-nbonenberger** [autopkg/apizz-recipes#88]
```
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/CodeSignatureVerifier.py", line 315, in main
    raise ProcessorError(
autopkglib.ProcessorError: Error processing path '/Users/admin/Library/AutoPkg/Cache/com.github.apizz.munki.MicrosoftTeams/MicrosoftTeams/Applications/Microsoft Teams.app' with glob. 
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Error processing path '/Users/admin/Library/AutoPkg/Cache/com.github.apizz.munki.MicrosoftTeams/MicrosoftTeams/Applications/Microsoft Teams.app' with glob. 
Failed.
```

```
The following recipes failed:
    com.github.apizz.munki.MicrosoftTeams
        Error in com.github.apizz.munki.MicrosoftTeams: Processor: CodeSignatureVerifier: Error: Error processing path '/Users/admin/Library/AutoPkg/Cache/com.github.apizz.munki.MicrosoftTeams/MicrosoftTeams/Applications/Microsoft Teams.app' with glob. 
```

**Comment by ggeerraalldd** [comment]
pull request #89 submitted
